[build]
  command = "npm run build"
  publish = "dist"  # Change this to "dist" since Vite outputs to "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200